pom.xml
src/main/java/org/folio/cache/VertxCache.java
src/main/java/org/folio/holdingsiq/model/Configuration.java
src/main/java/org/folio/holdingsiq/model/ConfigurationError.java
src/main/java/org/folio/holdingsiq/model/ObjectsForPostResourceResult.java
src/main/java/org/folio/holdingsiq/model/OkapiData.java
src/main/java/org/folio/holdingsiq/model/PackageResult.java
src/main/java/org/folio/holdingsiq/model/ResourceResult.java
src/main/java/org/folio/holdingsiq/model/TitleResult.java
src/main/java/org/folio/holdingsiq/model/VendorResult.java
src/main/java/org/folio/holdingsiq/service/ConfigurationService.java
src/main/java/org/folio/holdingsiq/service/HoldingsIQService.java
src/main/java/org/folio/holdingsiq/service/exception/ConfigurationInvalidException.java
src/main/java/org/folio/holdingsiq/service/impl/ConfigurationClientProvider.java
src/main/java/org/folio/holdingsiq/service/impl/ConfigurationServiceCache.java
src/main/java/org/folio/holdingsiq/service/impl/ConfigurationServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceImpl.java

Add Configuration Service code to the library
Take the code from mod-kb-ebso-java as a base. Copy content of `org.folio.config.*` to the library source and refactor.

MODCXEKB-85 Add Configuration Service code to the library

---

src/main/java/org/folio/holdingsiq/service/HoldingsIQService.java
src/main/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/urlbuilder/PackagesFilterableUrlBuilder.java
src/main/java/org/folio/holdingsiq/service/impl/urlbuilder/QueryableUrlBuilder.java
src/main/java/org/folio/holdingsiq/service/impl/urlbuilder/TitlesFilterableUrlBuilder.java

* changed modifier for retrieveProvider and retrieveResource methods to be able to use it in `mod-kb-ebsco-java` module
* fixed typo in filter name from `QueriableUrlBuilder` to `QueryableUrlBuilder`

MODCXEKB-85 - changed modifier for retrieveProvider and retrieveResource methods

---

pom.xml
src/test/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceImplTest.java
src/test/resources/responses/proxiescustomlabels/get-root-proxy-custom-labels-success-response.json

Implement common test set up for HoldingsIQService tests.
Use mockito to mock Vertx HttpClient and all related classes

MODCXEKB-85 Mock interaction with remote HoldingsIQ server, add sample test

---

src/main/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/HoldingsRequestHelper.java
src/main/java/org/folio/holdingsiq/service/impl/PackagesHoldingsIQServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/ProviderHoldingsIQServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/ResourcesHoldingsIQServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/TitlesHoldingsIQServiceImpl.java
src/test/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceImplTest.java

refactored code related to RMAPI functionality
* set `holdingsIQService` as constructor parameter 
* removed commented code inside HoldingsIQServiceImpl as the conversion will be implemented in `mod-kb-ebsco-java` which is using this method

MODCXEKB-85 - Extract RMAPIService to a library module

---

NEWS.md
pom.xml

Release the library for HoldingsIQ API

Tmp release 1.0.0

---

src/main/java/org/folio/holdingsiq/service/ProviderHoldingsIQService.java
src/main/java/org/folio/holdingsiq/service/impl/ProviderHoldingsIQServiceImpl.java

Make it possible for mod-kb-ebsco-java to depend on RM API endpoints that are not implemented yet 
Add unimplemented method to interface

MODKBEKBJ-187: Add method for getting providers by list of ids

---

src/main/java/org/folio/holdingsiq/model/Holding.java
src/main/java/org/folio/holdingsiq/model/Holdings.java
src/main/java/org/folio/holdingsiq/model/HoldingsLoadStatus.java
src/main/java/org/folio/holdingsiq/service/LoadService.java
src/main/java/org/folio/holdingsiq/service/impl/HoldingsRequestHelper.java
src/main/java/org/folio/holdingsiq/service/impl/LoadServiceImpl.java
src/test/java/org/folio/holdingsiq/service/impl/LoadServiceImplTest.java

As a part of https://issues.folio.org/browse/MODKBEKBJ-238 we need to be able to acquire information about staging snapshot. 
* created endpoints to communicate with a staging server
* added tests

MODKBEKBJ-238 - Create periodic task to populate holdings table

---

src/main/java/org/folio/holdingsiq/model/PackageByIdData.java
src/main/java/org/folio/holdingsiq/model/VendorById.java
src/main/java/org/folio/holdingsiq/service/PackagesHoldingsIQService.java
src/main/java/org/folio/holdingsiq/service/ResourcesHoldingsIQService.java
src/main/java/org/folio/holdingsiq/service/impl/PackagesHoldingsIQServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/ResourcesHoldingsIQServiceImpl.java

Use CompletableFuture instead of CompletionStage to make methods compatible
with code that uses them
Add VendorById#toByIdBuilder

Replace completionStage

---

src/main/java/org/folio/holdingsiq/model/PackagePut.java

Add "isFullPackage" to PackagePut

MODKBEKBJ-311: Add "isFullPackage" to PackagePut

---

src/main/java/org/folio/holdingsiq/model/CustomerResources.java
src/main/java/org/folio/holdingsiq/model/ResourceBase.java
src/main/java/org/folio/holdingsiq/model/ResourcePut.java
src/test/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceTestConfig.java

Add userDefinedFields to PUT /{custid}/vendors/{vendorid}/packages/{packageid}/titles/{kbid}

MODKBEKBJ-335: Add userDefinedFields to PUT /{custid}/vendors/{vendorid}/packages/{packageid}/titles/{kbid}

---

src/main/java/org/folio/holdingsiq/model/DeltaReport.java
src/main/java/org/folio/holdingsiq/model/DeltaReportParams.java
src/main/java/org/folio/holdingsiq/model/DeltaReportStatus.java
src/main/java/org/folio/holdingsiq/model/HoldingChangeType.java
src/main/java/org/folio/holdingsiq/model/HoldingInReport.java
src/main/java/org/folio/holdingsiq/model/HoldingsDownloadTransaction.java
src/main/java/org/folio/holdingsiq/model/HoldingsLoadTransactionStatus.java
src/main/java/org/folio/holdingsiq/model/HoldingsTransactionIdsList.java
src/main/java/org/folio/holdingsiq/model/TransactionId.java
src/main/java/org/folio/holdingsiq/service/LoadService.java
src/main/java/org/folio/holdingsiq/service/impl/HoldingsRequestHelper.java
src/main/java/org/folio/holdingsiq/service/impl/LoadServiceImpl.java
src/test/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceTestConfig.java
src/test/java/org/folio/holdingsiq/service/impl/LoadServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/impl/PackagesHoldingsIQServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/impl/ProviderHoldingsIQServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/impl/TitlesHoldingsIQServiceImplTest.java

Add new endpoints for story MODKBEKBJ-344
Add methods that call new endpoints to LoadService

MODKBEKBJ-344: Implement new Holdings IQ endpoints

---

pom.xml
src/main/java/org/folio/holdingsiq/service/impl/ConfigurationServiceImpl.java

* Fix ConfigurationServiceException creation
* update folio-service-tools version

MODCXEKB-103 - Fix ConfigurationServiceException creation

---

NEWS.md
pom.xml

Release 1.8.0

---

pom.xml
src/main/java/org/folio/holdingsiq/model/ResourcePut.java
src/main/java/org/folio/holdingsiq/service/validator/TitleParametersValidator.java
src/test/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceTestConfig.java
src/test/java/org/folio/holdingsiq/service/impl/LoadServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/impl/PackagesHoldingsIQServiceImplTest.java

FHIQC-1 - Update Vert.X to v3.9.0

---

src/main/java/org/folio/holdingsiq/service/impl/urlbuilder/QueryableUrlBuilder.java
src/main/java/org/folio/holdingsiq/service/impl/urlbuilder/TitlesFilterableUrlBuilder.java
src/test/java/org/folio/holdingsiq/service/builder/TitlesFilterableUrlBuilderTest.java
src/test/java/org/folio/holdingsiq/service/impl/TitlesHoldingsIQServiceImplTest.java

fix for  https://issues.folio.org/browse/MODKBEKBJ-515
* changed searchtype to 'contains'

MODKBEKBJ-515 - GET Titles search | change searchtype from advanced to contains

---

src/main/java/org/folio/holdingsiq/service/impl/ConfigurationServiceImpl.java

Return invalid configuration response when invalid url

MODKBEKBJ-550 Return invalid configuration response when invalid url

---

pom.xml

Upgrade to vertx 4.1
https://issues.folio.org/browse/FHIQC-11

FHIQC-11 Upgrade to vertx 4.1

---

pom.xml

Log4j vulnerability verification and correction

FHIQC-15 Log4j vulnerability verification and correction

---

src/main/java/org/folio/holdingsiq/model/AlternateTitle.java
src/main/java/org/folio/holdingsiq/model/Title.java

Add alternative titles information to the following GET title endpoint
GET /eholdings/titles

FHIQC-17 Include alternateTitle information with titles response

---

pom.xml
src/main/java/org/folio/holdingsiq/service/impl/HoldingsInteractionContext.java
src/main/java/org/folio/holdingsiq/service/impl/HoldingsRequestHelper.java

FHIQC-22 Upgrade vertx to v4.3.1

---

NEWS.md
pom.xml

- Update dependencies
- Update NEWS
https://issues.folio.org/browse/FHIQC-23

FHIQC-23 Upgrade to VertX 4.3.4

---

src/main/java/org/folio/holdingsiq/model/CustomerResources.java
src/main/java/org/folio/holdingsiq/model/Proxy.java
src/main/java/org/folio/holdingsiq/model/ProxyUrl.java
src/test/java/org/folio/holdingsiq/service/impl/ResourcesHoldingsIQServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/util/DataUtils.java

_Add this new field [proxiedUrl] TO GET /eholdings/resources/ {resourceId}_
_By adding this new field then the field will display on the View package-title (aka resource) record_
_Added a new field into Proxy class_

FHIQC-31: Update GET /eholdings/resources/resourceId to include proxiedUrl

---

src/main/java/org/folio/holdingsiq/service/LoadService.java
src/main/java/org/folio/holdingsiq/service/impl/LoadServiceImpl.java
src/test/java/org/folio/holdingsiq/service/impl/LoadServiceImplTest.java

- Use the force parameter for creating a snapshot
Closes: FHIQC-33

feat(load-holdings) Use the force parameter for creating a snapshot

---

pom.xml
src/main/java/org/folio/holdingsiq/service/validator/PackageParametersValidator.java
src/main/java/org/folio/holdingsiq/service/validator/TitleParametersValidator.java
src/test/java/org/folio/holdingsiq/service/validator/PackageParametersValidatorTest.java
src/test/java/org/folio/holdingsiq/service/validator/TitleParametersValidatorTest.java

chore: update dependencies

---

pom.xml

Update dependencies https://folio-org.atlassian.net/browse/FHIQC-38

fix: update dependencies

---

NEWS.md
pom.xml

Prepare for 3.3.0 development iteration

Prepare for 3.3.0 development iteration

---

Jenkinsfile
NEWS.md
pom.xml
src/main/java/org/folio/holdingsiq/model/OkapiData.java
src/main/java/org/folio/holdingsiq/model/Sort.java
src/main/java/org/folio/holdingsiq/service/impl/ConfigurationServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/HoldingsInteractionContext.java
src/main/java/org/folio/holdingsiq/service/impl/LoadServiceImpl.java
src/main/java/org/folio/holdingsiq/service/impl/urlbuilder/QueryableUrlBuilder.java
src/main/java/org/folio/holdingsiq/service/impl/urlbuilder/TitlesFilterableUrlBuilder.java
src/test/java/org/folio/holdingsiq/service/builder/PackagesFilterableUrlBuilderTest.java
src/test/java/org/folio/holdingsiq/service/config/ConfigurationServiceCacheTest.java
src/test/java/org/folio/holdingsiq/service/config/ConfigurationServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/impl/HoldingsIQServiceImplTest.java
src/test/java/org/folio/holdingsiq/service/impl/ResourcesHoldingsIQServiceImplTest.java

upgrade to Java 21
https://folio-org.atlassian.net/browse/FHIQC-40
- Upgrade to Java 21
- Fix sonar issues

chore: upgrade to Java 21

---

NEWS.md
src/main/java/org/folio/holdingsiq/service/impl/HoldingsRequestHelper.java

Cleanup sensitive data from logs.
reduce log verbosity and remove sensitive RMAPI data exposure

refactor: reduce log verbosity and remove sensitive RMAPI data exposure
